version: '3.7'

services:

  myproject:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']  # new
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - ADMIN_NAMESPACE=/cooladmin
      - DATABASE_URL=postgresql://postgres:postgres@myproject-db:5432/myproject_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@myproject-db:5432/myproject_test
    depends_on:
      - myproject-db
    stdin_open: true
    tty: true


  myproject-db:
    build:
      context: ./project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
